services:
  medilabo-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - medilabo-db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  medilabo-auth-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${AUTH_MYSQL}
      MYSQL_USER: ${AUTH_MYSQL_USER}
      MYSQL_PASSWORD: ${AUTH_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
    volumes:
      - medilabo-auth-db-data:/var/lib/mysql
      - ./db/auth-init.sql:/docker-entrypoint-initdb.d/auth-init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${AUTH_MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
  medilabo-notes-db:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NOTES_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${NOTES_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${NOTES_MONGO_DATABASE}
    volumes:
      - medilabo-notes-db:/data/db
      - ./db/notes-init.sh:/docker-entrypoint-initdb.d/notes-init.sh
      - ./db/notes-data.json:/docker-entrypoint-initdb.d/notes-data.json
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "${NOTES_MONGO_USER}", "-p", "${NOTES_MONGO_PASSWORD}", "--authenticationDatabase", "admin" ]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway:
    build: ./gateway
    depends_on:
      - patient
      - notes
      - auth
    ports:
      - "9090:9090"
    environment:
      GATEWAY_URI: ${PATIENT_URI}
      NOTES_URI: http://notes:9094
      AUTH_URI: http://auth:9093
      RISK_URI: http://risk:9095
      JWT_SECRET: ${JWT_SECRET}

  patient:
    build: ./patient
    environment:
      DB_URL: jdbc:mysql://medilabo-db:3306/${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      medilabo-db:
        condition: service_healthy
    ports:
      - "9091:9091"

  web:
    build: ./web
    environment:
      GATEWAY_URL: ${GATEWAY_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      gateway:
        condition: service_started
    ports:
      - "9092:9092"

  auth:
    build: ./auth
    environment:
      DB_URL: jdbc:mysql://medilabo-auth-db:3306/${AUTH_MYSQL}
      DB_USER: ${AUTH_MYSQL_USER}
      DB_PASSWORD: ${AUTH_MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      medilabo-auth-db:
        condition: service_healthy
    ports:
      - "9093:9093"

  notes:
    build: ./notes
    environment:
      MONGO_URI: mongodb://${NOTES_MONGO_USER}:${NOTES_MONGO_PASSWORD}@medilabo-notes-db:27017/${NOTES_MONGO_DATABASE}?authSource=admin
    depends_on:
      medilabo-notes-db:
        condition: service_healthy
    ports:
      - "9094:9094"
  risk:
    build: ./risk
    environment:
      GATEWAY_URL: ${GATEWAY_URI}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      gateway:
        condition: service_started
    ports:
      - "9095:9095"

  adminer:
    image: adminer
    depends_on:
      - medilabo-db
    ports:
      - "8081:8080"

volumes:
  medilabo-db-data:
  medilabo-auth-db-data:
  medilabo-notes-db:
