services:
  medilabo-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - medilabo-db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  medilabo-web-db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${WEB_MYSQL}
      MYSQL_USER: ${WEB_MYSQL_USER}
      MYSQL_PASSWORD: ${WEB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WEB_MYSQL_ROOT_PASSWORD}
    volumes:
      - medilabo-web-db-data:/var/lib/mysql
      - ./db/web-init.sql:/docker-entrypoint-initdb.d/web-init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${WEB_MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway:
    build: ./gateway
    depends_on:
      - patient
    ports:
      - "9090:9090"
    environment:
      GATEWAY_URI: ${PATIENT_URI}

  patient:
    build: ./patient
    environment:
      DB_URL: jdbc:mysql://medilabo-db:3306/${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      medilabo-db:
        condition: service_healthy
    ports:
      - "9091:9091"

  web:
    build: ./web
    environment:
      GATEWAY_URL: ${GATEWAY_URI}
      DB_URL: jdbc:mysql://medilabo-web-db:3306/${WEB_MYSQL}
      DB_USER: ${WEB_MYSQL_USER}
      DB_PASSWORD: ${WEB_MYSQL_PASSWORD}
    depends_on:
      gateway:
        condition: service_started
      medilabo-web-db:
          condition: service_healthy
    ports:
      - "9092:9092"

  adminer:
    image: adminer
    depends_on:
      - medilabo-db
    ports:
      - "8081:8080"

volumes:
  medilabo-db-data:
  medilabo-web-db-data:
