spring.application.name=patient
server.port=9091

spring.jpa.properties.jakarta.persistence.validation.mode=none
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}